In [9]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.4.2


In [10]:
# Do random matrices create karo (3x3)
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

print("Matrix A:")
print(A)
print("Shape of A:", A.shape)

print("\nMatrix B:")
print(B)
print("Shape of B:", B.shape)

Matrix A:
[[4 9 3]
 [7 2 1]
 [4 5 6]]
Shape of A: (3, 3)

Matrix B:
[[3 4 9]
 [5 7 4]
 [7 4 9]]
Shape of B: (3, 3)


In [11]:
# Element-wise multiplication (har position ka element multiply hoga)
elementwise_result = A * B

print("Element-wise Multiplication (A * B):")
print(elementwise_result)
print("Shape:", elementwise_result.shape)

Element-wise Multiplication (A * B):
[[12 36 27]
 [35 14  4]
 [28 20 54]]
Shape: (3, 3)


In [12]:
# Matrix multiplication (dot product)
matmul_result = np.matmul(A, B)

print("Matrix Multiplication (A @ B):")
print(matmul_result)
print("Shape:", matmul_result.shape)

Matrix Multiplication (A @ B):
[[ 78  91  99]
 [ 38  46  80]
 [ 79  75 110]]
Shape: (3, 3)


In [13]:
# Square matrix ka inverse aur determinant
print("Matrix A:")
print(A)

# Determinant
det = np.linalg.det(A)
print("\nDeterminant of A:", round(det, 4))

# Inverse (sirf tab possible hai jab determinant != 0)
if det != 0:
    inverse = np.linalg.inv(A)
    print("\nInverse of A:")
    print(np.round(inverse, 4))
    print("Shape of Inverse:", inverse.shape)
else:
    print("\nInverse nahi nikal sakta — Determinant 0 hai (Singular Matrix)!")

Matrix A:
[[4 9 3]
 [7 2 1]
 [4 5 6]]

Determinant of A: -233.0

Inverse of A:
[[-0.03    0.1674 -0.0129]
 [ 0.1631 -0.0515 -0.073 ]
 [-0.1159 -0.0687  0.2361]]
Shape of Inverse: (3, 3)


In [14]:
# 1D array banao
arr_1d = np.array([10, 20, 35, 50, 65, 80, 100])
print("Original 1D Array:", arr_1d)
print("Shape:", arr_1d.shape)

# Normalization formula: (x - min) / (max - min)
normalized = (arr_1d - arr_1d.min()) / (arr_1d.max() - arr_1d.min())

print("\nNormalized Array (range 0 to 1):")
print(np.round(normalized, 4))
print("Min after normalization:", normalized.min())
print("Max after normalization:", normalized.max())

Original 1D Array: [ 10  20  35  50  65  80 100]
Shape: (7,)

Normalized Array (range 0 to 1):
[0.     0.1111 0.2778 0.4444 0.6111 0.7778 1.    ]
Min after normalization: 0.0
Max after normalization: 1.0


In [15]:
# 2D array banao
matrix_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

print("Original 2D Matrix:")
print(matrix_2d)
print("Shape:", matrix_2d.shape)

# Har column ka mean nikalo
col_mean = matrix_2d.mean(axis=0)  # axis=0 = column-wise
print("\nColumn Means:", col_mean)
print("Shape of Column Means:", col_mean.shape)

# Broadcasting: har column se uska mean subtract karo
result = matrix_2d - col_mean

print("\nAfter Subtracting Column Mean (Broadcasting):")
print(result)
print("Shape:", result.shape)

# Verify: ab har column ka mean 0 hona chahiye
print("\nVerification — New Column Means (should be ~0):")
print(result.mean(axis=0))

Original 2D Matrix:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Shape: (4, 3)

Column Means: [55. 65. 75.]
Shape of Column Means: (3,)

After Subtracting Column Mean (Broadcasting):
[[-45. -45. -45.]
 [-15. -15. -15.]
 [ 15.  15.  15.]
 [ 45.  45.  45.]]
Shape: (4, 3)

Verification — New Column Means (should be ~0):
[0. 0. 0.]


In [ ]:
print("=" * 50)
print("       SUMMARY — NumPy Matrix Operations")
print("=" * 50)
print(f"1. Matrix A shape:              {A.shape}")
print(f"2. Matrix B shape:              {B.shape}")
print(f"3. Element-wise result shape:   {elementwise_result.shape}")
print(f"4. Matrix multiply result shape:{matmul_result.shape}")
print(f"5. Determinant of A:            {round(det, 4)}")
print(f"6. Normalized array min-max:    {normalized.min()} to {normalized.max()}")
print(f"7. 2D matrix shape:             {matrix_2d.shape}")
print(f"8. After broadcasting shape:    {result.shape}")
print("=" * 50)
print("All operations completed successfully! ")

       SUMMARY — NumPy Matrix Operations
1. Matrix A shape:              (3, 3)
2. Matrix B shape:              (3, 3)
3. Element-wise result shape:   (3, 3)
4. Matrix multiply result shape:(3, 3)
5. Determinant of A:            -233.0
6. Normalized array min-max:    0.0 to 1.0
7. 2D matrix shape:             (4, 3)
8. After broadcasting shape:    (4, 3)
All operations completed successfully! ✅
